stages:
  - test
  - lint

variables:
  DOCKER_DRIVER: "overlay2"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

test:
  stage: test
  image: golang:1.18

  tags:
    - test

  services:
    - name: docker:dind
      alias: localhost
      command: ["--tls=false"]

  script:
    - make test

lint:
  stage: lint
  image: docker

  tags:
    - test

  services:
    - name: docker:dind
      alias: localhost
      command: ["--tls=false"]

  before_script:
    - apk update
    - apk add --no-cache musl-dev make
  
  script:
    - make lint